site_name: S4P_MNIST
site_description: "machine learning for MNIST"
site_author: "Cindy Cai"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.highlight

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc
